CREATE TABLE Copy(
	DocID INT NOT NULL,
	CopyNO INT NOT NULL,
	LibID INT NOT NULL,
	Position VARCHAR(10) NOT NULL,
    PRIMARY KEY(DocID, CopyNO , LibID),
    FOREIGN KEY(DocID) REFERENCES Document(DocID),
	FOREIGN KEY(LibID) REFERENCES Branch(LibID)
 	);
	
CREATE TABLE Branch(
	LibID INT NOT NULL,
	Lname VARCHAR(20) NOT NULL,
	Llocation VARCHAR(20) NOT NULL,
	PRIMARY KEY(LibID)
	);
	
CREATE TABLE Reserves(
	ResNO INT NOT NULL,
	ReaderID INT NOT NULL,
	DocID INT NOT NULL,
	CopyNO INT NOT NULL,
	LibID INT NOT NULL,
	DTime DATETIME NOT NULL,
	PRIMARY KEY(ResNO),
	FOREIGN KEY(ReaderID) REFERENCES Reader(ReaderID),
	FOREIGN KEY(DocID,CopyNO,LibID) REFERENCES Copy(DocID,CopyNO,LibID)
	);
	
CREATE TABLE Borrows(
	BorNO INT NOT NULL,
	ReaderID INT NOT NULL,
    DocID INT NOT NULL,
	CopyNO INT NOT NULL,
	LibID INT NOT NULL,
	BDTime DATETIME NOT NULL,
    RDTime DATETIME NOT NULL, 	
	PRIMARY KEY(BorNO),
	FOREIGN KEY(ReaderID) REFERENCES Reader(ReaderID),
	FOREIGN KEY(DocID,CopyNO,LibID) REFERENCES Copy(DocID,CopyNO,LibID)
	);

CREATE TABLE Reader (
	ReaderID INT NOT NULL,
	RType VARCHAR(10) NOT NULL,
	RName VARCHAR(10) NOT NULL,
	Address VARCHAR(10) NOT NULL,
	PRIMARY KEY(ReaderID)     
	);